<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<!-- =========================================================
         PROJECT
         ========================================================= -->
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.6</version>
		<relativePath />
	</parent>

	<groupId>gov.com.ai</groupId>
	<artifactId>gst-return-3b-analysis</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>gst-return-3b-analysis</name>
	<description>
		GST Return 3B Analysis, Forecasting and AI Risk Prediction Engine
	</description>


	<!-- =========================================================
         PROPERTIES
         ========================================================= -->
	<properties>

		<!-- Java -->
		<java.version>17</java.version>

		<!-- Encoding -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- =====================================================
             XGBOOST

             IMPORTANT:
             Keep this version compatible with the version used
             to train/generate your .model files.
             ===================================================== -->
		<xgboost.version>1.7.5</xgboost.version>

		<!-- SpringDoc / Swagger -->
		<springdoc-openapi.version>2.8.5</springdoc-openapi.version>

	</properties>


	<!-- =========================================================
         DEPENDENCIES
         ========================================================= -->
	<dependencies>


		<!-- =====================================================
             WEB / REST API
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>

			<exclusions>
				<exclusion>
					<groupId>
						org.springframework.boot
					</groupId>
					<artifactId>
						spring-boot-starter-logging
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<!-- =====================================================
             LOG4J2
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>


		<!-- =====================================================
             SPRING JDBC
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>

			<exclusions>
				<exclusion>
					<groupId>
						org.springframework.boot
					</groupId>
					<artifactId>
						spring-boot-starter-logging
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<!-- =====================================================
             ORACLE DATABASE
             ===================================================== -->
		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc11</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- =====================================================
     SPRING CACHE
     @Cacheable / @CachePut / @CacheEvict
     ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>

		<!-- =====================================================
     CAFFEINE CACHE
     High-performance in-memory cache
     ===================================================== -->
		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
		</dependency>


		<!-- =====================================================
             BEAN VALIDATION
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>

			<exclusions>
				<exclusion>
					<groupId>
						org.springframework.boot
					</groupId>
					<artifactId>
						spring-boot-starter-logging
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<!-- =====================================================
             SPRING RETRY
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>
		</dependency>


		<!-- =====================================================
             ACTUATOR
             Health / Metrics / Monitoring
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>

			<exclusions>
				<exclusion>
					<groupId>
						org.springframework.boot
					</groupId>
					<artifactId>
						spring-boot-starter-logging
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<!-- =====================================================
             OPENAPI / SWAGGER
             ===================================================== -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc-openapi.version}</version>
		</dependency>


		<!-- =====================================================
             XGBOOST4J
             ===================================================== -->
		<dependency>
			<groupId>ml.dmlc</groupId>
			<artifactId>xgboost4j_2.12</artifactId>
			<version>${xgboost.version}</version>

			<exclusions>

				<!-- Prevent old Log4j binding -->
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>

				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>

			</exclusions>
		</dependency>


		<!-- =====================================================
             LOMBOK
             ===================================================== -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>


		<!-- =====================================================
             CONFIGURATION PROCESSOR
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>


		<!-- =====================================================
             DEVTOOLS

             Development only.
             It will not be packaged into the final application
             because it is optional.
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>


		<!-- =====================================================
             TEST
             ===================================================== -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>

			<exclusions>
				<exclusion>
					<groupId>
						org.springframework.boot
					</groupId>
					<artifactId>
						spring-boot-starter-logging
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

	</dependencies>


	<!-- =========================================================
         BUILD
         ========================================================= -->
	<build>

		<plugins>


			<!-- =================================================
                 SPRING BOOT MAVEN PLUGIN
                 ================================================= -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>

				<configuration>

					<!-- Do not package Lombok into production JAR -->
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>

				</configuration>
			</plugin>


			<!-- =================================================
                 MAVEN COMPILER
                 ================================================= -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>

				<configuration>

					<release>${java.version}</release>

					<parameters>true</parameters>

					<annotationProcessorPaths>

						<!-- Lombok -->
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>

						<!-- Spring Configuration Processor -->
						<path>
							<groupId>
								org.springframework.boot
							</groupId>
							<artifactId>
								spring-boot-configuration-processor
							</artifactId>
						</path>

					</annotationProcessorPaths>

				</configuration>
			</plugin>

		</plugins>

	</build>


</project>

